"""access group doors and personnel group memberships

Revision ID: 39d8af1b06df
Revises: 795ec8945bac
Create Date: 2026-09-16 12:56:05.308235
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "39d8af1b06df"
down_revision: str | None = "795ec8945bac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_group_doors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_group_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("door_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["access_group_id"], ["access_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "access_group_id", "device_id", "door_number", name="uq_access_group_door"
        ),
    )
    op.create_index(
        op.f("ix_access_group_doors_access_group_id"),
        "access_group_doors",
        ["access_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_group_doors_device_id"), "access_group_doors", ["device_id"], unique=False
    )
    op.create_table(
        "personnel_access_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("personnel_id", sa.Integer(), nullable=False),
        sa.Column("access_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["access_group_id"], ["access_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("personnel_id", "access_group_id", name="uq_personnel_access_group"),
    )
    op.create_index(
        op.f("ix_personnel_access_groups_access_group_id"),
        "personnel_access_groups",
        ["access_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personnel_access_groups_personnel_id"),
        "personnel_access_groups",
        ["personnel_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_personnel_access_groups_personnel_id"), table_name="personnel_access_groups"
    )
    op.drop_index(
        op.f("ix_personnel_access_groups_access_group_id"), table_name="personnel_access_groups"
    )
    op.drop_table("personnel_access_groups")
    op.drop_index(op.f("ix_access_group_doors_device_id"), table_name="access_group_doors")
    op.drop_index(op.f("ix_access_group_doors_access_group_id"), table_name="access_group_doors")
    op.drop_table("access_group_doors")
    # ### end Alembic commands ###
