"""initial schema

Revision ID: 795ec8945bac
Revises:
Create Date: 2026-09-16 12:11:34.188752
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "795ec8945bac"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("device_timezone_id", sa.Integer(), nullable=False),
        sa.Column("door_numbers", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("area", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("serial_number", sa.String(length=64), nullable=True),
        sa.Column("firmware_version", sa.String(length=128), nullable=True),
        sa.Column("mac_address", sa.String(length=32), nullable=True),
        sa.Column("lock_count", sa.Integer(), nullable=True),
        sa.Column("reader_count", sa.Integer(), nullable=True),
        sa.Column("max_user_count", sa.Integer(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("personnel_count", sa.Integer(), nullable=True),
        sa.Column("last_log_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip", "port", name="uq_device_ip_port"),
    )
    op.create_index(op.f("ix_devices_serial_number"), "devices", ["serial_number"], unique=False)
    op.create_table(
        "access_logs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_serial", sa.String(length=64), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_code", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=True),
        sa.Column("card_number", sa.String(length=32), nullable=True),
        sa.Column("employee_id", sa.String(length=32), nullable=True),
        sa.Column("door_number", sa.Integer(), nullable=True),
        sa.Column("verification_mode", sa.String(length=64), nullable=True),
        sa.Column("in_out_status", sa.String(length=32), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_access_log_dedupe"),
    )
    op.create_index(
        op.f("ix_access_logs_card_number"), "access_logs", ["card_number"], unique=False
    )
    op.create_index(
        "ix_access_logs_device_time", "access_logs", ["device_id", "event_time"], unique=False
    )
    op.create_index(
        op.f("ix_access_logs_employee_id"), "access_logs", ["employee_id"], unique=False
    )
    op.create_table(
        "door_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("door_number", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("end_time", sa.String(length=5), nullable=False),
        sa.Column("device_timezone_id", sa.Integer(), nullable=False),
        sa.Column("normal_open", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "door_number", "day_of_week", name="uq_door_schedule"),
    )
    op.create_table(
        "personnel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("card_number", sa.String(length=32), nullable=True),
        sa.Column("pin", sa.String(length=32), nullable=True),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_group_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["access_group_id"], ["access_groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_number", name="uq_personnel_card_number"),
        sa.UniqueConstraint("employee_id", name="uq_personnel_employee_id"),
    )
    op.create_index(op.f("ix_personnel_device_id"), "personnel", ["device_id"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_runs_device_id"), "sync_runs", ["device_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_runs_device_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_personnel_device_id"), table_name="personnel")
    op.drop_table("personnel")
    op.drop_table("door_schedules")
    op.drop_index(op.f("ix_access_logs_employee_id"), table_name="access_logs")
    op.drop_index("ix_access_logs_device_time", table_name="access_logs")
    op.drop_index(op.f("ix_access_logs_card_number"), table_name="access_logs")
    op.drop_table("access_logs")
    op.drop_index(op.f("ix_devices_serial_number"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("access_groups")
    # ### end Alembic commands ###
