"""access time zones

Revision ID: 907835756e6e
Revises: 39d8af1b06df
Create Date: 2026-09-16 13:17:19.609001
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

revision: str = "907835756e6e"
down_revision: str | None = "39d8af1b06df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_time_zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("device_timezone_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_24_hour", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_timezone_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "access_time_zone_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_zone_id", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("end_time", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(["time_zone_id"], ["access_time_zones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("time_zone_id", "day_of_week", "slot", name="uq_time_zone_slot"),
    )
    op.create_index(
        op.f("ix_access_time_zone_slots_time_zone_id"),
        "access_time_zone_slots",
        ["time_zone_id"],
        unique=False,
    )

    # Seed the "24 Jam" zone. Every panel in this deployment already runs on
    # slot 1 (ZKAccess `acc_timeseg` 1 = "24-Hour Accessible"), and all migrated
    # access levels point at it, so without this row they would reference a
    # time zone that has no definition.
    now = datetime.now(timezone.utc)
    zones = sa.table(
        "access_time_zones",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("device_timezone_id", sa.Integer),
        sa.column("description", sa.Text),
        sa.column("is_24_hour", sa.Boolean),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    op.bulk_insert(
        zones,
        [
            {
                "id": 1,
                "name": "24 Jam",
                "device_timezone_id": 1,
                "description": "Akses penuh 24 jam, setiap hari (00:00-23:59)",
                "is_24_hour": True,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    slots = sa.table(
        "access_time_zone_slots",
        sa.column("time_zone_id", sa.Integer),
        sa.column("day_of_week", sa.Integer),
        sa.column("slot", sa.Integer),
        sa.column("start_time", sa.String),
        sa.column("end_time", sa.String),
    )
    op.bulk_insert(
        slots,
        [
            {
                "time_zone_id": 1,
                "day_of_week": day,
                "slot": index + 1,
                "start_time": start,
                "end_time": end,
            }
            for day in range(7)
            for index, (start, end) in enumerate(
                [("00:00", "23:59"), ("00:00", "00:00"), ("00:00", "00:00")]
            )
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_access_time_zone_slots_time_zone_id"), table_name="access_time_zone_slots"
    )
    op.drop_table("access_time_zone_slots")
    op.drop_table("access_time_zones")
    # ### end Alembic commands ###
